from groq import Groq
from config import Config
from services.prompt_service import get_system_prompt

# Initialize Groq client
client = Groq(api_key=Config.GROQ_API_KEY)

# Best free model — Llama 3.3 70B, excellent Urdu support
MODEL = "llama-3.3-70b-versatile"


def get_ai_response(flow: str, language: str, messages: list, user_message: str) -> str:
    """
    Sends conversation to Groq (Llama 3.3) and returns AI response.
    Groq is free, fast, and has no region restrictions.
    """
    try:
        system_prompt = get_system_prompt(flow, language)

        # Build message history in OpenAI format (Groq uses same format)
        history = [{"role": "system", "content": system_prompt}]

        for msg in messages:
            if msg["role"] == "user":
                history.append({"role": "user", "content": msg["text"]})
            elif msg["role"] == "ai":
                history.append({"role": "assistant", "content": msg["text"]})

        # Add current user message
        history.append({"role": "user", "content": user_message})

        # Call Groq API
        response = client.chat.completions.create(
            model=MODEL,
            messages=history,
            temperature=0.7,
            max_tokens=1000,
        )

        return response.choices[0].message.content

    except Exception as e:
        print(f"GROQ ERROR: {str(e)}")
        error_messages = {
            "roman_urdu": "Maafi chahti hun, abhi connection mein masla aa gaya. Thodi der baad dobara koshish karein. 🙏",
            "urdu":       "معذرت، ابھی connection میں مسئلہ آ گیا۔ تھوڑی دیر بعد دوبارہ کوشش کریں۔ 🙏",
            "english":    "I'm sorry, there seems to be a connection issue. Please try again in a moment. 🙏"
        }
        return error_messages.get(language, error_messages["roman_urdu"])


def generate_doctor_card_content(symptoms: str, duration: str,
                                  severity: str, language: str) -> str:
    """
    Generates a structured doctor visit card using Groq.
    """
    try:
        prompts = {
            "roman_urdu": f"""
Ek structured doctor visit card banao in symptoms ke liye:
Symptoms: {symptoms}
Muddat (Duration): {duration}
Severity: {severity}

Card format:
🩺 DOCTOR VISIT SUMMARY
━━━━━━━━━━━━━━━━━━━━━━

📋 SYMPTOMS (Alamat):
[List each symptom clearly]

⏱ DURATION (Muddat):
[Duration information]

📊 SEVERITY (Shaddat):
[Severity level]

🔬 MEDICAL TERMS:
[Relevant medical terminology for the doctor]

❓ QUESTIONS FOR DOCTOR:
[2-3 suggested questions to ask]

━━━━━━━━━━━━━━━━━━━━━━
Generated by SamajhHer
            """,
            "urdu": f"""
ان علامات کے لیے ایک structured doctor visit card بنائیں:
علامات: {symptoms}
مدت: {duration}
شدت: {severity}
کارڈ اردو میں بنائیں۔ ڈاکٹر 30 سیکنڈ میں پڑھ سکے۔
            """,
            "english": f"""
Generate a structured doctor visit card for:
Symptoms: {symptoms}
Duration: {duration}
Severity: {severity}
Format it clearly so a doctor can read it in 30 seconds.
Include relevant medical terminology.
            """
        }

        prompt = prompts.get(language, prompts["roman_urdu"])

        response = client.chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": "You are a medical assistant helping prepare structured doctor visit summaries."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.3,
            max_tokens=800,
        )

        return response.choices[0].message.content

    except Exception as e:
        print(f"CARD GENERATION ERROR: {str(e)}")
        return "Card generation failed. Please try again."